apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ci-cd-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
